### ISSUE TITLE
Cache book data

### ISSUE THREAD

**Issue by HuiiBuh** [Goodwy/PlayBook#10]
First of all. I really like your audiobook player and it recently replaced the smart audiobook player with PlayBooks.

### Problem:
If you open the player and the player is not cached in RAM you see that he loads the books in the *not started* category. It looks like the player parses the directory for new books after every startup and does not cache the books he already found.

### Solution:
Cache every book you find and display them at startup time. Then run your ebook search and add then new books/remove books which are not longer on the device. 

And just a tiny nitpick. I think the material spec uses dark shadows for elevation (In your case the currently playing book overlay)
[https://material.io/design/color/dark-theme.html#behavior](https://material.io/design/color/dark-theme.html#behavior), but if you prefer it your way go ahead and keep it

**Comment by Goodwy** [comment]
Hi. Thanks for the advice. I was just looking for a solution with dark
shadows.

вс, 17 окт. 2021 г. в 11:11, HuiiBuh ***@***.***>:

**Comment by Goodwy** [comment]
Fixed in version 2.0
