### ISSUE TITLE
Problem with app remembering position in book

### ISSUE THREAD

**Issue by rabfulton** [Goodwy/PlayBook#13]
If I close and reopen the app it will forget my position in the audio book. I have found this is dependent on whether the book scanned as a "folder with single book" (app will remember position) or "folder with multiple subfolders", (app forgets position).

Android 10 with the latest paid version of the application.

**Comment by Goodwy** [comment]
Does the problem still exist in version 2.0?

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
