### ISSUE TITLE
Audio book won't play

### ISSUE THREAD

**Issue by TDderpy** [Goodwy/PlayBook#15]
I have a m4a audio book that i cant get to play. The player will see the audio book and i can select times, chapters ect but when i hit the play button it animates to the pause button but i get no sound and then a moment later it animates back to the play button with the time not progressing.

I've tried other audio books i have in the same format and they have no issues playing.

Its possibly due to the length of the audiobook, as its a very large 28GB audio book with a total run length of 200hours plus, but i have no proof this is the case currently.

Happy to troubleshoot with you as needed let me know.

**Comment by Goodwy** [comment]
Does the problem still exist in version 2.0?

**Comment by TDderpy** [comment]
> Does the problem still exist in version 2.0?

Honestly no idea, after not receiving a response I switched to another app.
