### ISSUE TITLE
Make the App available on F-Droid / IzzyOnDroid 

### ISSUE THREAD

**Issue by RuthlessRuler** [Goodwy/PlayBook#21]
I wanted to know if there are any plans to make the App available through F-droid. 
This will allow app to be more available to people who tend to follow & use OSS more. 

If not f-droid, IzzyOnDroid is also a good place too.

**Comment by Poussinou** [comment]
Would it be possible to get a signed Release APK in the [Release Section](https://github.com/Goodwy/PlayBook/releases)?

**Comment by Goodwy** [comment]
Starting from version 4.0.0 the apk files will be available in the [Release Section](https://github.com/Goodwy/PlayBook/releases)

**Comment by hachikoharuno** [comment]
Why don't you want to host your apps on F-droid?
