### ISSUE TITLE
Playbooks app crashes without opening after January 2nd 2023 update

### ISSUE THREAD

**Issue by piersonjarvis** [Goodwy/PlayBook#28]
App started crashing today after the update last night/this morning. Running on a samsung s21+ (SM-G996U) running android 13 update (G996USQS5DVL3)

**Comment by felislynx-silae** [comment]
Same on pixel 4xl and redmi note 10

**Comment by blueclochard** [comment]
Same issue for me with version 1.3.6. The app opens and then immediately closes again. The widget also no longer works. Google Pixel 4 with Android 13 here.

A temporary solution for those with the same problem: the free version Playbooks Lite was not updated and still works.

**Comment by piersonjarvis** [comment]
I actually got a second update the same day that fixed the issue.

**Comment by blueclochard** [comment]
I just got an update to 1.3.7 as well. This fixes it.

**Comment by Goodwy** [comment]
Fixed in version 2.0
