### ISSUE TITLE
Sleep timer shake to reset

### ISSUE THREAD

**Issue by ShawnPConroy** [Goodwy/PlayBook#3]
Using the sleep timer function often works well. But occasionally it's hard to get to sleep. But opening my eyes, navigating my phone and looking at the screen would wake me up even more.

Solution: use the accelerometer to be able to shake or flip the phone over and have the sleep timer restart. The genius of this design is that it doesn't get in the way of the using the audiobook.

This is a really nice feature that I didn't know I liked until I heard about it. Now I cannot stop thinking about it.

**Comment by Goodwy** [comment]
Within 30 seconds after the end of the sleep timer, you can shake the phone and the sleep timer will restart. Do you want to be able to do this before the sleep timer ends?

**Comment by ShawnPConroy** [comment]
Oh, that's great! I didn't realize that at all.

Yes, please during it too. I like that feature. I set it for 10 minutes. 5 minutes in I realize I will need more time, so I pre-emptively wiggle it. Or set the timer as I am getting ready for bed and just wiggle it as I lay down so I don't even have to look at the screen.

**Comment by ShawnPConroy** [comment]
Also, that give me a visual indication that there is such a feature and I wouldn't have missed it. I, much prefer making it, so it doesn't get interrupted, as well as the above.

**Comment by Goodwy** [comment]
Fixed
