### ISSUE TITLE
Folder Structure & edit options broken/limited in 2.0

### ISSUE THREAD

**Issue by callsignesh** [Goodwy/PlayBook#30]
### Overview

Recently updated to 2.0, and noticed a few options have been removed, making the app unusable:

The folder structure no longer allows Author based subfolders:
![Screenshot_20230226-125100~2](https://user-images.githubusercontent.com/39025257/221388019-77d4a970-735e-48ef-a1c0-0e5f4c2ab29d.png)
![Screenshot_20230226-124949](https://user-images.githubusercontent.com/39025257/221388036-b952b3d0-79bf-4353-8bf3-8af1e378ff47.png)

And the edit options have removed the edit author function:
![Screenshot_20230226-125028](https://user-images.githubusercontent.com/39025257/221388046-1196e476-76af-44e8-8d85-24b525099e0a.png)
![Screenshot_20230226-125011~2](https://user-images.githubusercontent.com/39025257/221388053-79d5e2ed-f033-4692-8220-6a24ba7e18a1.png)

Please fix or provide an update. I don't want to roll back to lite as it doesn't have a dark function.

### How to reproduce

It's just broken - there is no replication

### Version

2.0.0

### Android Version

33

### Device Model

A063

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
