### ISSUE TITLE
Can't see any of my audiobook or event the interface.

### ISSUE THREAD

**Issue by Lemmy1892** [Goodwy/PlayBook#31]
### Overview

Selected a folder containing my audiobooks. I cannot find even the interface to play the audio.

### How to reproduce

1.Open the App
2. Select the folder
3. Audiobook player interface does not show up and even the audiobooks don't show up.

### Version

1.9.7

### Android Version

13

### Device Model

SM-A127F

**Comment by Lemmy1892** [comment]
Please could you elaborate, if possible with steps. Still struggling 😪.

**Comment by Goodwy** [comment]
On the main screen, click the Folders button and add a directory with books or a file with a book.

**Comment by Lemmy1892** [comment]
Please it is still not working.

**Comment by Goodwy** [comment]
At what stage do the difficulties arise? Attach a screenshot or screen recording.

**Comment by Lemmy1892** [comment]
![Uploading Screenshot_20230301_194625_PlayBook.jpg…]()

**Comment by Lemmy1892** [comment]
This was after I selected a book folder

**Comment by Lemmy1892** [comment]
This was after I selected a book folder and still the same problem.

**Comment by Goodwy** [comment]
Screenshot not showing

**Comment by Lemmy1892** [comment]
![Screenshot_20230301_194625_PlayBook](https://user-images.githubusercontent.com/126659565/222259867-b7e864e3-e227-4f5a-a7e6-4485b9424ab5.jpg)

**Comment by Lemmy1892** [comment]
This was after I added a directory

**Comment by Goodwy** [comment]
This is a screenshot of the main screen. You need to click the Folders button, then press the Add button and select a directory with books or a file.

**Comment by Goodwy** [comment]
Try reinstalling the app and preferably install the latest version.

**Comment by Lemmy1892** [comment]
I did so but still the audiobooks won't show.

**Comment by Goodwy** [comment]
There may be no supported audio files in the specified directory.
