### ISSUE TITLE
Constant crashing 

### ISSUE THREAD

**Issue by BlueBli** [Goodwy/PlayBook#33]
### Overview

while using the app on a samsung a20 fe 5g the latest version of the app is crashing constantly. 

### How to reproduce

1. open the app
2. play a book
3. app crash after about 5 ninutes of playback

or by tinkering in the settings for too long

### Version

2.0.0

### Android Version

33

### Device Model

SM-G781B

**Comment by Goodwy** [comment]
Need an error log.

**Comment by ttabi** [comment]
How does one get an error log?  I'm also experiencing this problem -- after about 5/10 minutes, when my phone starts the process of going to sleep (i.e. the screen dims a bit), right about then the app just seems to exit.

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
