### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by sd-system** [Goodwy/PlayBook#35]
### Overview

Titles of chapters in Russian are incorrectly read.

### How to reproduce

When opening a book in Russian, instead of chapter titles, something incomprehensible

### Version

2.0.0

### Android Version

33

### Device Model

SM-S918B

**Comment by sd-system** [comment]
![Screenshot_20230330_080329_PlayBook](https://user-images.githubusercontent.com/128981596/228735721-d0bd915d-376c-4167-868d-56d26a9ef95b.jpg)

**Comment by Goodwy** [comment]
The title has incorrect coding, you need to change the title.
