### ISSUE TITLE
Audiobooks list doesn't appear 

### ISSUE THREAD

**Issue by amine2731** [Goodwy/PlayBook#36]
### Overview

After the selection of the source file for my audiobooks, I find the space blank and I can't access any audiobook.

### How to reproduce

Open the app 
Click on folders
Choose a source
Return to the main space
Find nothing.

### Version

2.1.0

### Android Version

28

### Device Model

JKM-LX2

**Comment by Goodwy** [comment]
Try changing the name of the book folder.

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
