### ISSUE TITLE
Occasional Crashes

### ISSUE THREAD

**Issue by avadaca** [Goodwy/PlayBook#37]
### Overview

Hi, I have been experiencing crashes that happen occasionally when I am using my phone or at least leave the screen on during listening. 

### How to reproduce

This happens within the app and when I have it playing in the background.
Then it shows the that the app is not responding leading up to a crash. 
It crashes without me doing any other demanding tasks, it crashes even when I am on the homescreen without touching the phone.

See error log:
![20230417_235957](https://user-images.githubusercontent.com/131064122/232620163-cc5ec912-dc5b-46a8-aa61-fe8a50698e41.jpg)

### Version

Palybook Version 2.1.0

### Android Version

Android 12

### Device Model

Poco x3 nfc

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
