### ISSUE TITLE
Book title in media player notification doesn't work properly

### ISSUE THREAD

**Issue by JurianOnderwater** [Goodwy/PlayBook#40]
### Overview

The book title in the media player in the notification shade only displays '1'.
![Screenshot_20230515-173957](https://github.com/Goodwy/PlayBook/assets/61699997/12dad265-c606-49be-8db7-0693fac152f7)

### How to reproduce

1. Play an audiobook named '1'
2. Rename audiobook to actual title and play again
3. Check media player

### Version

2.1.0

### Android Version

13

### Device Model

Pixel 7

**Comment by Goodwy** [comment]
This is where the information from the other tag is displayed; it displays the chapter name, not the book name.
