### ISSUE TITLE
After pausing an audiobook and leaving the app in the background 

### ISSUE THREAD

**Issue by KlimaRitter** [Goodwy/PlayBook#42]
### Overview

 After pausing an audiobook and leaving the app in the, when i want to resume it, the play button doesnt do anything. It is fixable by either playing a different audiobook for a short time and then playing the first one again, or by closing the app an reopening it 

### How to reproduce

1. Pause an Audiobook
2. Leave the App in the background
3. Reopen it and play the audiobook again
4. It doesnt play 

### Version

2.1.0

### Android Version

33

### Device Model

M2102J20SG

**Comment by Goodwy** [comment]
Check on the current version.
