### ISSUE TITLE
Support for Nested Folders under nested folders

### ISSUE THREAD

**Issue by RuthlessRuler** [Goodwy/PlayBook#43]
### Overview

So I have my AudioBook collection in such structure:

AudioBooks -> Author -> Book

Since there can be multiple books from same author, it becomes easy for me to find.

But the App creates one giant audiobook from such structure.

### How to reproduce

1. Launch App
2. Go to Folders
3. Add the desired nested Folders
4. Choose the option of Root folder

### Version

2.2.0

### Android Version

31

### Device Model

Poco X3 Pro

**Comment by Goodwy** [comment]
In your case, you don't need to add the folder with the audiobooks, but the folder with the author.

**Comment by Goodwy** [comment]
Implemented on version 3.0.0+
