### ISSUE TITLE
Hey, can you add this in next update 

### ISSUE THREAD

**Issue by Knull04** [Goodwy/PlayBook#47]
### Overview

This is not for bug or glitch but I want to know is there any for separate windows for not started, going and complete audiobook is really hard to manage everything on single page and sometimes is become annoying please 😔🥺 and at last there is a feature in swipe to change chapter and make an option to enable or disable it. 

### How to reproduce

?

### Version

3.0.0

### Android Version

13

### Device Model

Poco X3

**Comment by Goodwy** [comment]
There is no such feature right now.
