### ISSUE TITLE
Quick settings media controls card not showing correct chapter

### ISSUE THREAD

**Issue by jjstader** [Goodwy/PlayBook#48]
### Overview

The media playback card in quick settings (swipe down from the status bar) is stuck showing the first chapter of the book even though the app shows i am on chapter 10. Would probably be better to show the correct chapter name or even just the book name in quick settings 

### How to reproduce

1. Open the app
2. Pick a book with multiple chapters
3. Play a chaper other than the first
4. Swipe down from the status bar and the media player will show the first chapter name.

### Version

3.0.0

### Android Version

13

### Device Model

Pixel 7a

**Comment by Goodwy** [comment]
Check after installing version 4.0.0+.
