### ISSUE TITLE
Incorrect reading of books metadata

### ISSUE THREAD

**Issue by igorcretu** [Goodwy/PlayBook#49]
### Overview

![Screenshot_20230921-025921_PlayBook](https://github.com/Goodwy/PlayBook/assets/64871246/fbcc471f-94eb-4b35-908d-c3d6884282c0)

Unfortunately some books titles and other metadata is being read incorrectly

### How to reproduce

Using some russian books

### Version

3.0.0

### Android Version

Android 13

### Device Model

Oneplus 8 Pro

**Comment by altair86** [comment]
Problem in `ffprobe` execute app when trying `analyze` for MetaData. In my case there is result:
```
{
      "streams": [
          {  }
      ],
      "chapters": [
  
      ],
      "format": { "duration": "365.035000",
          "tags": { "album": "ÐÐ»Ð°Ð´Ð¸ÑÐ»Ð°Ð² ÐÑÐ°Ð¿Ð¸Ð²Ð¸Ð½ - Ð¡Ð°Ð¼Ð¾Ð»ÐµÑ Ð¿Ð¾ Ð¸Ð¼ÐµÐ½Ð¸ Ð¡ÐµÑÐµÐ¶ÐºÐ°", "artist": "ÐÐ³Ð¾ÑÑ ÐÐ½ÑÐ·ÐµÐ²", "title": "01 ÐÐ°Ð»ÐºÐ¾Ð½Ð½ÑÐ¹ Ð¶Ð¸ÑÐµÐ»Ñ  -  01" } }
  }
```
This text in UTF-8 (because when I open it with `Notepad++` it's ok on that charset), but this can't read correctly in Windows with `ffprobe` and with `Mp3Tag` app.
Maybe we need to try change utility for reading of Metadata.

**Comment by altair86** [comment]
We can 
`ffprobe.exe -print_format json=c=1 -show_entries format=duration -show_entries format_tags=artist,title,album -show_entries stream_tags=artist,title,album example of file.mp3 > abc.txt
`
Example of file:
https://drive.google.com/file/d/1AFk2OhigDQwyJwKfl9Stsoq2QgG_nOji/view?usp=sharing

**Comment by Goodwy** [comment]
We are aware of this problem, but we can't fix it yet. This happens if the name is not encoded correctly. You can manually rename the book inside the application, then the name will be displayed correctly.
