### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by 7enChan** [Goodwy/PlayBook#54]
### Overview

During the use of the app, occasional crashes may occur.

### How to reproduce

1. Open the app and start listening to audiobooks, return to the home screen, listen continuously for about 30 minutes.
2. Open the app again from the desktop icon.
3. App crashes.

### Version

3.0.0

### Android Version

11

### Device Model

HITV205N

**Comment by Goodwy** [comment]
Check after installing version 4.0.0+.
