### ISSUE TITLE
Player skips ahead

### ISSUE THREAD

**Issue by jade62000111** [Goodwy/PlayBook#55]
### Overview

When paused after listening for a while and running the app in the background or with the screen locked the timestamp does not match the actual location I listened to last. Often it is several minutes ahead. I have to rewind to find my place.

### How to reproduce

1. Open app
2. Play the audiobook for 30+ minutes
3. Press pause 
4. Press play

### Version

3.0.0

### Android Version

34

### Device Model

Pixel 6 Pro

**Comment by mykhail0** [comment]
I have the same issue. My hypothesis is the timer on the track counts at a faster rate (from my own observation) and when you resume playing the audio track it resumes using the saved timestamp

**Comment by Goodwy** [comment]
Check after installing version 4.0.0+.
