### ISSUE TITLE
lock screen tile, and pull down tile not working.

### ISSUE THREAD

**Issue by garnetbugbee** [Goodwy/PlayBook#57]
### Overview

I've gone through all of my settings to make sure it's not just my phone, but it seems like the lock screen tile, and the pull down tile do not work when I try to use any of the buttons. 

### How to reproduce

1. Pull down from the top of the screen, or on the lock screen.
2. Click play
3. Nothing happens
4. The widget works fine though.

### Version

3.0.0

### Android Version

34

### Device Model

Pixel 6a

**Comment by Goodwy** [comment]
Check after installing version 4.0.0+.
