### ISSUE TITLE
time left in audiobook says 749 hours??

### ISSUE THREAD

**Issue by rabbjty** [Goodwy/PlayBook#58]
### Overview

the audiobook is 10 hours and 17 minutes but for some reason the "end credits" section is over 700 hours long. when I open the same file in VLC it doesn't do that so I don't think it's a problem with the file.

![Screenshot_20231229-090029](https://github.com/Goodwy/PlayBook/assets/155174692/f880dce6-64b4-44ca-a171-2dac1725f6aa)

![Screenshot_20231229-090018](https://github.com/Goodwy/PlayBook/assets/155174692/7336990f-a4ea-4729-9a5f-ca10e0320ba2)

### How to reproduce

1. open app
2. look at the audiobooks downloaded
3. says 1% complete and 749 hours left

### Version

3.0.0

### Android Version

14

### Device Model

Pixel 4a

**Comment by Goodwy** [comment]
Will be fixed in version 4.0.0.

**Comment by The-Ducktor** [comment]
![Screenshot_20240827-092412](https://github.com/user-attachments/assets/cc395dfa-03df-4664-9aff-f30e06ade998)
Had a similar issue, fine in VLC but 600+ hours in playbook

**Comment by The-Ducktor** [comment]
![Screenshot_20240827-073101](https://github.com/user-attachments/assets/32c1652a-28cd-46ce-8e42-ce6b32fdf2bf)
Similar issue normal time in VLC but 600+ hours in playbook
