### ISSUE TITLE
Delete book or add cover will not work

### ISSUE THREAD

**Issue by Dottedd** [Goodwy/PlayBook#60]
### Overview

I long click the book from the list of books and whatever I choose, it just sits there. I've tried deleting the app and install it back multiple times. Deleting data and cache and deleting. Everything. I can't have a fresh start.
![Screenshot_20240212_171402_PlayBook](https://github.com/Goodwy/PlayBook/assets/159762849/f6ba5e41-ece6-4c87-b096-cc07ee401429)

### How to reproduce

1.Open app
2.Long click book
3.Click delete book
4.Just goes back to the list as if I clicked nothing.(same goes for the book cover too)

### Version

3.0.0

### Android Version

33

### Device Model

SM-G986N

**Comment by Goodwy** [comment]
Update to the latest version of the application, no problems are observed.
