### ISSUE TITLE
m4a format causes crash

### ISSUE THREAD

**Issue by beerda** [Goodwy/PlayBook#61]
### Overview

When trying to add a book with files in the m4a format, the application closes immediately on every subsequent restart.

### How to reproduce

1. Add a book in m4a format.
2. The app exits immediately.
3. Start the app again.
4. The app exits immediately.

### Version

3.0.0

### Android Version

33

### Device Model

motorola edge 40

**Comment by Goodwy** [comment]
I downloaded the first m4a file from the internet, it plays without errors. Please check if your file is correct or send it to us.
