### ISSUE TITLE
Problema riproduzione audiolibri

### ISSUE THREAD

**Issue by chiaraic** [Goodwy/PlayBook#63]
### Overview

Buongiorno, oggi ho notato che quando avvio la app continua a scorrere la barra di "caricamento" e se provo a riprodurre un audiolibro non parte. Grazie

### How to reproduce

1. Apro la app
2. Vedo la modalità "caricamento" che continua senza fermarsi
3. Audio non parte anche se schiaccio play

### Version

3.0.0

### Android Version

34

### Device Model

SM-A528B

**Comment by Goodwy** [comment]
Verificare che l'applicazione abbia accesso alla memoria in cui sono memorizzati i libri. Se il percorso dei libri è stato modificato, è necessario aggiungerli di nuovo.
