### ISSUE TITLE
Playback speed options

### ISSUE THREAD

**Issue by ShawnPConroy** [Goodwy/PlayBook#7]
It's often frustrating to get the slider exactly where I want it to change the playback speed. Especially if I am walking, or want it set really quickly.

It would be easier to have a dialog appear that shows the speed and a + and - button to do .1 increments. And tapping the current speed could switch between 1.0, 1.5 and 2.0.

Alternatively, having a few buttons below the slider for 1.0, 1.25, 1.5, 1.75 and 2.0 could work as well.

**Comment by Goodwy** [comment]
Fixed in version 2.0
