### ISSUE TITLE
Audiobooks(1)

### ISSUE THREAD

**Issue by Likebubble** [Goodwy/PlayBook#71]
### Overview

I accidentally deleted this folder and now the folder is deleted from my internal storage too. Please help me restore this folder. I have many audiobooks in there. 

### How to reproduce

1. Opened the app
2. Tried to remove folder 
3. The folder gets deleted

### Version

4.0.2

### Android Version

30

### Device Model

V2043_21

**Comment by Goodwy** [comment]
Hi. Once a folder is deleted, it cannot be recovered. There are special programs that can recover deleted media files, maybe they will help.
