### ISSUE TITLE
No audiobook found

### ISSUE THREAD

**Issue by BejalKahn** [Goodwy/PlayBook#73]
### Overview

The app doesn't found any file in the selected folder (internal memory of the device)

### How to reproduce

1. Open the app
2. Select the folder
3. Select the way the folder is organized (any selection made the same result)

### Version

4.0.3

### Android Version

34

### Device Model

SM-S928B

**Comment by Goodwy** [comment]
If there are files in the folder, try either renaming the folder or moving the files to another folder.

**Comment by BejalKahn** [comment]
I tried to use a single folder for each book and it seems to work correctly. I recently change device and in the past with my previous one I never had this problem: all the file were in one single directory but on an SD card.
Since I hadn't used the app in a while, I thought it might be due to a recent update my problem, my bad.
Thank you for you quick answer and for this amazing app.
