### ISSUE TITLE
Missing Chapter (but the file exists and plays fine)

### ISSUE THREAD

**Issue by intrepidclass** [Goodwy/PlayBook#78]
### Overview

Was listening to my audiobook when I noticed a chapter was missing. (No. 27). I have a no idea why it wasn't included.

### How to reproduce

![Screenshot_20240803_001645_Files by Google](https://github.com/user-attachments/assets/6720993c-571f-4365-90c0-9f4aab3d309c)

I can share a copy of the book or the specific chapter if that helps to reproduce.

![Screenshot_20240803_001528_PlayBook](https://github.com/user-attachments/assets/e7f96a7d-ddb5-4a3f-bb1c-d585fd9347d3)

### Version

4.0.2

### Android Version

14

### Device Model

Galaxy S23 plus

**Comment by Goodwy** [comment]
Hi. Can you send us chapter 26 and 27 to goodwy.dev@gmail.com?
I suspect that file 27 has a different chapter number in the tags.

**Comment by intrepidclass** [comment]
Sorry I made a mistake: I do also have the mp3 files per chapter on my
device, but PlayBook is reading from an m4b file. I think this file is
corrupt because another m4b Player also doesn't play that chapter.
We can close/delete this issues.



Op zo 4 aug 2024 10:47 schreef Goodwy ***@***.***>:
