### ISSUE TITLE
Missing M4B Chapter Data

### ISSUE THREAD

**Issue by ShawnPConroy** [Goodwy/PlayBook#8]
When playing M4B files, the chapter data is missing. Rather than consistently showing the chapter name from the metadata, what happens depends on the file type:

**MP3 audiobooks**
The app correctly shows the file title metadata as the chapter name in the app, in the notification widget, on Bluetooth and Android Auto.

**Single-file M4B audiobooks**
In single file M4B audiobooks it correctly shows the chapter metadata in the app, but:
* the notification area doesn't show any chapter info, and
* on Bluetooth displays and Android Auto it shows an alternate version of the book title instead of the chapter name, along with book title as album name. (So the book title is shown twice, once as track title and once as album, and they are grabbed from different pieces of metadata.)

**Multi-file split M4B audiobooks**
Again, in multi-file split M4B audiobooks it correctly shows the chapter metadata in the app, but:
* In the notification area, Bluetooth displays and Android Auto it shows the title of the first chapter in the current file. ~~the file number (track number?) rather than the chapter name from the metadata. (In my case, that's around 18 chapters of '1' as the track title on Bluetooth.)~~

---

Using ExifTool on Android I noticed that Audible files converted to M4B list a short name in 'Album' and a long name with sub-title in 'Title'. However, the split M4Bs from Downpour don't have a title. I might recommend using the Title name with Album as fallback for M4B files, unless the full title makes it too cluttered.

Also, I noticed that M4B do have a 'track ID' and it might be this metadata the app uses for multi-file split M4B audiobooks for the chapter name in the notification and Bluetooth.

**Comment by ShawnPConroy** [comment]
One error I discovered in the above. It does not show the file number. Multi-file split M4B audiobooks shows the first chapter for each M4B file. So the first M4B files contained chapters 1-19, and shows 1. Until the second file started to play. It now shows 20 for each chapter on the Bluetooth display, and I assume the notification area and Android Auto.

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
