### ISSUE TITLE
Kitapta dosya seçme olanağı yok

### ISSUE THREAD

**Issue by Fazileskin** [Goodwy/PlayBook#81]
### Overview

Uygulama gayet kullanışlı fakat önceki dosyayı ya da sonraki dosya seçeneğini bulamadım dosya seçme olanağının olması gerekiyor diye düşünüyorum

### How to reproduce

Oy sağında ya da solunda dosya seç menüsünün bulunması iyi olur

### Version

4.0.2

### Android Version

Ant 14

### Device Model

SM-A045F

**Comment by Goodwy** [comment]
Bir kitap içindeki dosyaları seçmek için, bölümlerin listesini açan bir düğme vardır. Ayrıca kapak üzerinde kaydırarak da bölümler arasında geçiş yapabilirsiniz.
